version: '3.8'
services:
  client-dev:
    image: client-dev
    container_name: client-dev
    hostname: onebox-dev
    env_file:
      - .env
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    networks:
      onebox-network: {}

  client-prd:
    image: client-prd
    container_name: client-prd
    hostname: onebox-prd
    env_file:
      - .env.production
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3010:3010'
    networks:
      onebox-network: {}

networks:
  onebox-network:
    external: true
