FROM node:18-alpine as baseprod
RUN apk add --no-cache g++ make py3-pip libc6-compat
EXPOSE 3010

FROM base as builder
WORKDIR /app
COPY . .
RUN yarn build


FROM baseprod as production
WORKDIR /app

ENV NODE_ENV=production
RUN yarn install --network-timeout 1000000


RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
USER nextjs


COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public

CMD yarn start

